import { useState, useEffect } from 'react';
import { useLocation } from 'wouter';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Shield, RefreshCw, Download, Upload, CheckCircle, AlertTriangle } from 'lucide-react';

interface BackupEntry {
  timestamp: string;
  routeMap: Record<string, string>;
  description: string;
  version: string;
  isAutoGenerated: boolean;
}

interface RestoreOperation {
  id: string;
  fromRoute: string;
  toRoute: string;
  timestamp: string;
  success: boolean;
  errorMessage?: string;
}

export default function URLBackupRestoreSystem() {
  const [location, setLocation] = useLocation();
  const [backupEntries, setBackupEntries] = useState<BackupEntry[]>([]);
  const [restoreHistory, setRestoreHistory] = useState<RestoreOperation[]>([]);
  const [selectedBackup, setSelectedBackup] = useState<string>('');
  const [isRestoring, setIsRestoring] = useState(false);

  // VaultMesh complete route mapping for backup/restore
  const currentRouteMap = {
    // Core routes
    '/': 'VaultMesh Home Dashboard',
    '/sectors': 'Industry Sectors Overview',
    '/terminal': 'VaultMesh Terminal',
    '/packages': 'Global Packages & Pricing',
    '/agrochain': 'AgroChain Protocol',
    '/analytics': 'VaultMesh Analytics Dashboard',
    '/login': 'Authentication Portal',
    '/signup': 'Registration Portal',
    
    // Sector routes
    '/sectors/tech': 'Technology Sector Solutions',
    '/sectors/finance': 'Finance Sector Solutions', 
    '/sectors/health': 'Healthcare Sector Solutions',
    '/sectors/energy': 'Energy Sector Solutions',
    '/sectors/agriculture': 'Agriculture Sector Solutions',
    '/sectors/transport': 'Transportation Sector Solutions',
    
    // Subscription routes
    '/subscribe/starter': 'Agriculture & Biotech Starter Package',
    '/subscribe/pro': 'Agriculture & Biotech Pro Package',
    '/subscribe/enterprise': 'Agriculture & Biotech Enterprise Package',
    
    // Company routes
    '/features': 'VaultMesh Core Features',
    '/pricing': 'VaultMesh Pricing Overview',
    '/security': 'VaultMesh Security Framework',
    '/integrations': 'VaultMesh Integration Hub',
    '/about': 'About VaultMesh & Fruitful Team',
    '/careers': 'VaultMesh Career Opportunities',
    '/press': 'VaultMesh Press & Media',
    '/contact': 'VaultMesh Contact & Support',
    
    // Resources routes
    '/docs': 'VaultMesh Documentation',
    '/api': 'VaultMesh API Reference',
    '/blog': 'VaultMesh Blog & Updates',
    '/support': 'VaultMesh Support Center',
    '/learn': 'VaultMesh Learning Center',
    
    // Legal routes
    '/privacy': 'VaultMesh Privacy Policy',
    '/terms': 'VaultMesh Terms of Service', 
    '/cookies': 'VaultMesh Cookie Policy',
    '/gdpr': 'VaultMesh GDPR Compliance'
  };

  // Create automatic backup
  const createBackup = (description?: string, isAuto = false) => {
    const backup: BackupEntry = {
      timestamp: new Date().toISOString(),
      routeMap: { ...currentRouteMap },
      description: description || `${isAuto ? 'Auto-' : ''}Backup of VaultMesh routes`,
      version: '3.2.1',
      isAutoGenerated: isAuto
    };

    setBackupEntries(prev => [backup, ...prev.slice(0, 49)]); // Keep last 50 backups
    
    // Store in localStorage
    const storedBackups = JSON.parse(localStorage.getItem('vaultmesh-route-backups') || '[]');
    storedBackups.unshift(backup);
    localStorage.setItem('vaultmesh-route-backups', JSON.stringify(storedBackups.slice(0, 50)));
    
    return backup;
  };

  // Restore from backup
  const restoreFromBackup = async (backupId: string) => {
    setIsRestoring(true);
    
    try {
      const backup = backupEntries.find(b => b.timestamp === backupId);
      if (!backup) {
        throw new Error('Backup not found');
      }

      // Create restore operation record
      const restoreOp: RestoreOperation = {
        id: `restore-${Date.now()}`,
        fromRoute: location,
        toRoute: backup.routeMap[location] ? location : '/',
        timestamp: new Date().toISOString(),
        success: false
      };

      // Validate backup integrity
      const requiredRoutes = ['/', '/sectors', '/terminal', '/packages', '/agrochain'];
      const missingRoutes = requiredRoutes.filter(route => !backup.routeMap[route]);
      
      if (missingRoutes.length > 0) {
        restoreOp.errorMessage = `Missing critical routes: ${missingRoutes.join(', ')}`;
        restoreOp.success = false;
      } else {
        // Perform restoration (in a real system, this would update routing tables)
        console.log('[VaultMesh Backup] Restoring route configuration from backup:', backup.timestamp);
        
        // Simulate restoration success
        restoreOp.success = true;
        
        // If current route doesn't exist in backup, redirect to home
        if (!backup.routeMap[location]) {
          setLocation('/');
          restoreOp.toRoute = '/';
        }
      }

      setRestoreHistory(prev => [restoreOp, ...prev.slice(0, 19)]); // Keep last 20 operations
      
      // Store restore history
      const storedHistory = JSON.parse(localStorage.getItem('vaultmesh-restore-history') || '[]');
      storedHistory.unshift(restoreOp);
      localStorage.setItem('vaultmesh-restore-history', JSON.stringify(storedHistory.slice(0, 20)));

    } catch (error) {
      console.error('[VaultMesh Backup] Restore failed:', error);
      const failedOp: RestoreOperation = {
        id: `restore-failed-${Date.now()}`,
        fromRoute: location,
        toRoute: location,
        timestamp: new Date().toISOString(),
        success: false,
        errorMessage: error instanceof Error ? error.message : 'Unknown error'
      };
      setRestoreHistory(prev => [failedOp, ...prev]);
    } finally {
      setIsRestoring(false);
    }
  };

  // Export backup data
  const exportBackups = () => {
    const exportData = {
      backups: backupEntries,
      restoreHistory,
      currentRouteMap,
      exportTimestamp: new Date().toISOString(),
      vaultMeshVersion: '3.2.1',
      metadata: {
        totalBackups: backupEntries.length,
        totalRestores: restoreHistory.length,
        successfulRestores: restoreHistory.filter(r => r.success).length,
        lastBackup: backupEntries[0]?.timestamp,
        lastRestore: restoreHistory[0]?.timestamp
      }
    };

    const blob = new Blob([JSON.stringify(exportData, null, 2)], { 
      type: 'application/json' 
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `vaultmesh-backup-restore-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Import backup data
  const importBackups = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const data = JSON.parse(e.target?.result as string);
        if (data.backups && Array.isArray(data.backups)) {
          setBackupEntries(data.backups);
          localStorage.setItem('vaultmesh-route-backups', JSON.stringify(data.backups));
        }
        if (data.restoreHistory && Array.isArray(data.restoreHistory)) {
          setRestoreHistory(data.restoreHistory);
          localStorage.setItem('vaultmesh-restore-history', JSON.stringify(data.restoreHistory));
        }
      } catch (error) {
        console.error('[VaultMesh Backup] Import failed:', error);
      }
    };
    reader.readAsText(file);
    
    // Reset input
    event.target.value = '';
  };

  // Initialize backup system
  useEffect(() => {
    // Load stored backups
    const storedBackups = localStorage.getItem('vaultmesh-route-backups');
    if (storedBackups) {
      try {
        setBackupEntries(JSON.parse(storedBackups));
      } catch (error) {
        console.warn('[VaultMesh Backup] Failed to load stored backups:', error);
      }
    }

    // Load stored restore history
    const storedHistory = localStorage.getItem('vaultmesh-restore-history');
    if (storedHistory) {
      try {
        setRestoreHistory(JSON.parse(storedHistory));
      } catch (error) {
        console.warn('[VaultMesh Backup] Failed to load restore history:', error);
      }
    }

    // Create initial backup if none exists
    if (backupEntries.length === 0) {
      createBackup('Initial system backup', true);
    }

    // Set up automatic backups every hour
    const autoBackupInterval = setInterval(() => {
      createBackup(undefined, true);
    }, 60 * 60 * 1000);

    return () => clearInterval(autoBackupInterval);
  }, []);

  return (
    <Card className="bg-gray-900/50 border-gray-700">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-green-400 flex items-center gap-2">
              <Shield className="h-5 w-5" />
              URL Backup & Restore System
            </CardTitle>
            <CardDescription>
              Comprehensive backup and restoration for VaultMesh routing system
            </CardDescription>
          </div>
          <div className="flex gap-2">
            <Button 
              onClick={() => createBackup('Manual backup')}
              variant="outline"
              size="sm"
            >
              Create Backup
            </Button>
            <Button 
              onClick={exportBackups}
              variant="outline"
              size="sm"
            >
              <Download className="h-4 w-4 mr-1" />
              Export
            </Button>
            <Button 
              onClick={() => document.getElementById('backup-import')?.click()}
              variant="outline"
              size="sm"
            >
              <Upload className="h-4 w-4 mr-1" />
              Import
            </Button>
            <input
              id="backup-import"
              type="file"
              accept=".json"
              style={{ display: 'none' }}
              onChange={importBackups}
            />
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Status Overview */}
        <div className="grid grid-cols-3 gap-4">
          <div className="text-center p-3 bg-gray-800/50 rounded">
            <div className="text-xl font-bold text-green-400">{backupEntries.length}</div>
            <div className="text-xs text-gray-400">Total Backups</div>
          </div>
          <div className="text-center p-3 bg-gray-800/50 rounded">
            <div className="text-xl font-bold text-blue-400">{restoreHistory.length}</div>
            <div className="text-xs text-gray-400">Restore Operations</div>
          </div>
          <div className="text-center p-3 bg-gray-800/50 rounded">
            <div className="text-xl font-bold text-purple-400">
              {Object.keys(currentRouteMap).length}
            </div>
            <div className="text-xs text-gray-400">Protected Routes</div>
          </div>
        </div>

        {/* Restore Interface */}
        <div className="space-y-3">
          <h4 className="font-medium text-white">Restore from Backup</h4>
          <div className="flex gap-2">
            <Select value={selectedBackup} onValueChange={setSelectedBackup}>
              <SelectTrigger className="flex-1">
                <SelectValue placeholder="Select backup to restore" />
              </SelectTrigger>
              <SelectContent>
                {backupEntries.slice(0, 10).map((backup) => (
                  <SelectItem key={backup.timestamp} value={backup.timestamp}>
                    {new Date(backup.timestamp).toLocaleString()} - {backup.description}
                    {backup.isAutoGenerated && (
                      <Badge variant="secondary" className="ml-2 text-xs">AUTO</Badge>
                    )}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Button 
              onClick={() => selectedBackup && restoreFromBackup(selectedBackup)}
              disabled={!selectedBackup || isRestoring}
              variant="destructive"
            >
              {isRestoring ? (
                <RefreshCw className="h-4 w-4 mr-1 animate-spin" />
              ) : null}
              Restore
            </Button>
          </div>
        </div>

        {/* Recent Backups */}
        <div className="space-y-2">
          <h4 className="font-medium text-white">Recent Backups</h4>
          <div className="space-y-1 max-h-48 overflow-y-auto">
            {backupEntries.slice(0, 8).map((backup) => (
              <div 
                key={backup.timestamp} 
                className="flex items-center justify-between p-2 bg-gray-800/30 rounded text-sm"
              >
                <div className="flex items-center space-x-2">
                  <CheckCircle className="h-4 w-4 text-green-400" />
                  <span className="text-white">{backup.description}</span>
                  {backup.isAutoGenerated && (
                    <Badge variant="outline" className="text-xs">AUTO</Badge>
                  )}
                </div>
                <span className="text-gray-400 text-xs">
                  {new Date(backup.timestamp).toLocaleString()}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* Restore History */}
        {restoreHistory.length > 0 && (
          <div className="space-y-2">
            <h4 className="font-medium text-white">Restore History</h4>
            <div className="space-y-1 max-h-32 overflow-y-auto">
              {restoreHistory.slice(0, 5).map((operation) => (
                <div 
                  key={operation.id} 
                  className={`flex items-center justify-between p-2 rounded text-sm ${
                    operation.success ? 'bg-green-500/10' : 'bg-red-500/10'
                  }`}
                >
                  <div className="flex items-center space-x-2">
                    {operation.success ? (
                      <CheckCircle className="h-4 w-4 text-green-400" />
                    ) : (
                      <AlertTriangle className="h-4 w-4 text-red-400" />
                    )}
                    <span className="text-white text-xs">
                      {operation.fromRoute} → {operation.toRoute}
                    </span>
                  </div>
                  <span className="text-gray-400 text-xs">
                    {new Date(operation.timestamp).toLocaleTimeString()}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Emergency Restore Alert */}
        <Alert className="border-yellow-500/20 bg-yellow-500/10">
          <AlertTriangle className="h-4 w-4 text-yellow-500" />
          <AlertDescription className="text-yellow-400">
            <strong>Emergency Restore:</strong> If the current route fails, the system will automatically attempt backup route restoration.
          </AlertDescription>
        </Alert>
      </CardContent>
    </Card>
  );
}